apiVersion: apps/v1
kind: Deployment
metadata:
  name: "demo"
spec:
  selector:
    matchLabels:
      app: "demo"
  template:
    metadata:
      labels:
        app: "demo"
    spec:
      containers:
        - name: "demo"
          image: "localhost:5000/demo"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "demo"
data:
  application.yaml: |
    poc.configmap: Hello, I am using ConfigMap!